### ISSUE TITLE
Set Whitelist

### ISSUE THREAD

**Issue by Darkforcee** [public-awesome/stargaze-studio#27]
i cannot execute WL contract. got error "Set_whitelist execute failed!"

Error: Query failed with (18): failed to execute message; message index: 0: Generic error: Querier contract error: codespace: wasm, code: 8: execute wasm contract failed: invalid request

**Comment by MightOfOaks** [comment]
Before allowing the user to set a new whitelist, the current minter contract checks whether there already is a whitelist contract associated with itself and if there is one, it queries the associated whitelist contract to check whether it is active or not. The problem here is, the whitelist contract address associated with your minter contract did not belong to an actual whitelist contract (but rather to one of the whitelisted addresses directly), hence it was not able to properly respond to the query made by the minter contract, which resulted in an error.

We'll work on a way to validate specified whitelist contract addresses on the UI. The issue will also be addressed on future iterations of Stargaze's minter contract.
